name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what the problem is and your proposed solution.
      placeholder: I'm always frustrated when... I would like to be able to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: dropdown
    id: importance
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Critical (I can't use the tool without this)
        - High (Would improve my workflow significantly)
        - Medium (Nice to have)
        - Low (Polishing/Cosmetic)
